export const noteStyles = {
  background: "bg-[#030617] min-h-screen text-white font-sans overflow-x-hidden",
  navbar: "flex items-center justify-between px-8 py-5 bg-[#020B2D] border-b border-white/5",
  logoContainer: "flex items-center gap-3",
  logoIcon: "w-8 h-8 bg-[#8B5CF6] text-white flex items-center justify-center font-bold text-lg rounded-md",
  logoText: "text-xl font-semibold tracking-wide text-[#8B5CF6]",
  navMenu: "hidden lg:flex items-center gap-8",
  navItem: "text-[13px] font-semibold text-gray-200 hover:text-white transition-colors cursor-pointer",
  navItemActive: "px-6 py-2 bg-gradient-to-r from-[#9333EA] to-[#D946EF] rounded-full text-white text-[13px] font-semibold shadow-[0_0_15px_rgba(147,51,234,0.4)] cursor-pointer",
  rightIcons: "flex items-center gap-6",
  iconButton: "text-gray-300 hover:text-white transition-colors relative cursor-pointer",
  notificationDot: "absolute -top-0.5 right-0.5 w-2 h-2 bg-[#EF4444] rounded-full border-[1.5px] border-[#020B2D]",
  avatar: "w-8 h-8 bg-[#1E293B] border border-white/10 rounded-full flex items-center justify-center text-[11px] font-bold tracking-wider cursor-pointer",
  mainContent: "px-8 md:px-16 py-12 max-w-[1400px] mx-auto",
  headerSection: "flex justify-between items-center mb-10",
  pageTitle: "text-[40px] font-black tracking-tight",
  searchContainer: "relative w-[340px]",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 w-[16px] h-[16px] text-gray-400",
  searchInput: "w-full bg-[#131B3E] border border-blue-900/40 focus:border-[#8B5CF6]/50 rounded-full py-3 pl-11 pr-5 text-sm text-gray-200 placeholder-gray-400 focus:outline-none transition-all",
  grid: "grid grid-cols-[repeat(auto-fill,minmax(240px,280px))] gap-5 justify-start",
  card: "w-full max-w-[280px] bg-[#0B1333] rounded-[18px] p-4 relative group transition-all border border-white/5 flex flex-col h-full",
  cardInteractive: "cursor-pointer hover:-translate-y-0.5 hover:shadow-[0_10px_40px_rgba(2,8,30,0.5)]",
  cardHeader: "flex justify-between items-start mb-4 gap-3",
  cardTitle: "text-[12px] font-bold tracking-[0.25em] text-gray-100 uppercase flex-1 break-words",
  cardIcons: "flex items-center gap-3 pt-0.5",
  cardIcon: "w-4 h-4 text-gray-400 hover:text-white cursor-pointer transition-colors",
  pinIconActive: "w-4 h-4 text-[#EF4444] cursor-pointer",
  pinIconInactive: "w-4 h-4 text-gray-400 hover:text-white cursor-pointer",
  cardDesc: "text-[14px] text-[#94A3B8] leading-relaxed min-h-[96px] font-medium flex-1",
  cardDate: "text-[11px] font-bold text-gray-400 mt-4 tracking-widest mt-auto",
  fab: "fixed bottom-10 right-10 w-[56px] h-[56px] rounded-full border-[1.5px] border-white flex items-center justify-center text-white hover:bg-white/10 transition-all cursor-pointer z-50",
  bottomLeftIcon: "fixed bottom-10 left-10 w-10 h-10 bg-black/50 rounded-full border-[1.5px] border-white/10 flex items-center justify-center text-gray-400 cursor-pointer hover:bg-white/10 transition-colors z-50",
  editorOverlay: "fixed inset-0 z-[80] bg-[#020615]/58 backdrop-blur-[4px] flex items-center justify-center p-4 sm:p-6",
  editorDialog: "w-full max-w-[930px] h-[min(72vh,590px)] rounded-[30px] border border-[#27365F] bg-[#040B2D]/95 shadow-[0_24px_72px_rgba(1,6,24,0.95)] overflow-hidden",
  editorScroll: "h-full overflow-y-auto note-editor-scroll",
  editorHeader: "flex items-center justify-between px-7 py-5 border-b border-[#1E2F56]",
  editorTitleWrap: "flex items-center gap-3",
  editorTitleIconWrap: "w-[40px] h-[40px] rounded-[11px] bg-[#1A2646] border border-[#314775] flex items-center justify-center text-[#ADC1E4]",
  editorHeadingGroup: "space-y-1",
  editorTitle: "text-[20px] leading-none font-extrabold tracking-tight text-white",
  editorSubTitle: "text-[10px] tracking-[0.22em] font-semibold text-[#8FA0C4] uppercase",
  editorCloseButton: "w-10 h-10 rounded-full bg-[#1A2546] border border-[#1A2546] flex items-center justify-center text-[#90A5C7] hover:text-white hover:border-[#48629A] transition-colors cursor-pointer",
  editorToolbar: "flex items-center justify-between gap-3 px-5 py-3 border-b border-[#1E2F56]",
  editorToolbarLeft: "flex items-center gap-2",
  editorSeparator: "mx-1 h-6 w-px bg-[#28406F]",
  editorToolButton: "h-[40px] min-w-[40px] px-3 rounded-[12px] border border-[#2C406A] bg-[#0A1636] text-[#92A6C8] hover:text-white transition-all duration-200 flex items-center justify-center cursor-pointer hover:shadow-[0_0_12px_rgba(68,95,168,0.25)]",
  editorToolButtonActive: "h-[40px] min-w-[40px] px-3 rounded-[12px] border border-[#4A63A4] bg-[#273969] text-[#FFBE41] shadow-[0_0_16px_rgba(76,102,171,0.36)] flex items-center justify-center cursor-pointer",
  editorPinButton: "h-[40px] px-4 rounded-[12px] border border-[#2C406A] bg-[#0A1636] text-[#92A6C8] hover:text-white transition-all duration-200 flex items-center justify-center gap-2 cursor-pointer hover:shadow-[0_0_12px_rgba(68,95,168,0.25)]",
  editorPinButtonActive: "h-[40px] px-4 rounded-[12px] border border-[#4961A1] bg-[#263868] text-[#F5BE4E] shadow-[0_0_16px_rgba(76,102,171,0.36)] flex items-center justify-center gap-2 cursor-pointer",
  editorColorGroup: "grid grid-cols-5 gap-2",
  editorColorButton: "w-5 h-5 rounded-full border border-transparent transition-transform hover:scale-105 cursor-pointer",
  editorColorButtonActive: "w-5 h-5 rounded-full border-2 border-white shadow-[0_0_0_2px_rgba(5,11,36,0.95)]",
  editorContent: "px-7 py-5 space-y-5",
  editorSubjectRow: "flex items-center gap-3 rounded-[18px] border border-[#2C426D] bg-[#091533] px-5 py-3",
  editorSubjectInput: "flex-1 bg-transparent text-[17px] font-semibold text-white placeholder-[#5C7097] outline-none",
  editorCount: "text-[15px] font-semibold text-[#6E84AA]",
  editorBodyCard: "rounded-[22px] border border-[#2F4E86] bg-[#111F4C] h-[300px] px-6 py-5 transition-colors duration-300 overflow-hidden flex flex-col",
  editorTextColorRow: "flex items-center gap-3 mb-5",
  editorTextColorButton: "w-6 h-6 rounded-full border border-white/20 hover:scale-105 transition-transform cursor-pointer",
  editorTextColorButtonActive: "w-6 h-6 rounded-full border-2 border-white shadow-[0_0_0_2px_rgba(16,31,76,0.9)]",
  editorTextarea: "w-full min-h-[210px] bg-transparent resize-none outline-none text-[16px] leading-[1.55] placeholder-[#9AA9C8]",
  previewOverlay: "fixed inset-0 z-[85] bg-[#020615]/64 backdrop-blur-[5px] flex items-center justify-center p-4 sm:p-6",
  previewDialog: "w-full max-w-[760px] h-[min(84vh,760px)] rounded-[28px] border border-[#2C426D] bg-[#060F2D] shadow-[0_28px_74px_rgba(2,8,28,0.95)] overflow-hidden",
  previewHeader: "flex items-center justify-between px-6 py-5 border-b border-[#233A67]",
  previewTitleWrap: "space-y-1",
  previewTitle: "text-[20px] leading-tight font-extrabold tracking-tight text-white",
  previewDate: "text-[11px] tracking-[0.16em] font-semibold uppercase text-[#8EA4CD]",
  previewCloseButton: "w-10 h-10 rounded-full bg-[#1A2546] border border-[#27406E] flex items-center justify-center text-[#90A5C7] hover:text-white hover:border-[#4A6AA8] transition-colors cursor-pointer",
  previewBody: "px-6 py-5 overflow-y-auto h-[calc(84vh-88px)] note-preview-scroll",
  previewContentBox: "rounded-[20px] border border-[#2A4370] bg-[#0A1738] px-5 py-4 min-h-full",
};
