export const revisionStyles = {
  background: "bg-[#030617] min-h-screen text-white font-sans overflow-x-hidden",
  navbar: "flex items-center justify-between px-8 py-5 bg-[#020B2D] border-b border-white/5",
  logoContainer: "flex items-center gap-3",
  logoIcon: "w-8 h-8 bg-[#8B5CF6] text-white flex items-center justify-center font-bold text-lg rounded-md",
  logoText: "text-xl font-semibold tracking-wide text-[#8B5CF6]",
  navMenu: "hidden lg:flex items-center gap-8",
  navItem: "text-[13px] font-semibold text-gray-200 hover:text-white transition-colors cursor-pointer",
  navItemActive: "px-6 py-2 bg-gradient-to-r from-[#9333EA] to-[#D946EF] rounded-full text-white text-[13px] font-semibold shadow-[0_0_15px_rgba(147,51,234,0.4)] cursor-pointer",
  rightIcons: "flex items-center gap-6",
  iconButton: "text-gray-300 hover:text-white transition-colors relative cursor-pointer",
  notificationDot: "absolute -top-0.5 right-0.5 w-2 h-2 bg-[#EF4444] rounded-full border-[1.5px] border-[#020B2D]",
  avatar: "w-8 h-8 bg-[#1E293B] border border-white/10 rounded-full flex items-center justify-center text-[11px] font-bold tracking-wider cursor-pointer",
  
  mainContent: "px-8 md:px-16 py-12 max-w-[1400px] mx-auto",
  headerSection: "flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-6",
  headerTextGroup: "flex flex-col gap-2",
  pageTitle: "text-[40px] font-black tracking-tight",
  pageSubtitle: "text-gray-400 text-sm font-medium",
  
  searchWrapper: "flex items-center gap-4 w-full md:w-auto",
  searchContainer: "relative w-full md:w-[340px]",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 w-[16px] h-[16px] text-gray-400",
  searchInput: "w-full bg-[#131B3E] border border-blue-900/40 focus:border-[#8B5CF6]/50 rounded-full py-3 pl-11 pr-5 text-sm text-gray-200 placeholder-gray-400 focus:outline-none transition-all",
  searchAddButton: "w-[48px] h-[48px] rounded-full bg-[#7C3AED] hover:bg-[#6D28D9] flex items-center justify-center text-white transition-colors flex-shrink-0 cursor-pointer shadow-[0_0_15px_rgba(124,58,237,0.3)]",
  
  grid: "grid grid-cols-[repeat(auto-fill,minmax(240px,280px))] gap-5 justify-start",
  
  card: "w-full max-w-[280px] bg-[#0B1333] rounded-[18px] overflow-hidden transition-all duration-300 border border-white/5 hover:border-[#8B5CF6]/30 hover:shadow-[0_12px_30px_rgba(139,92,246,0.18)] group flex flex-col h-full",
  
  cardGradientBg: "relative h-[138px] w-full bg-cover bg-center flex items-center justify-center",
  cardMenuBtn: "absolute top-3 right-3 text-white/60 hover:text-white transition-colors opacity-0 group-hover:opacity-100",
  cardIconContainer: "flex items-center justify-center w-full h-full",
  cardIcon: "text-4xl drop-shadow-lg",
  
  cardContent: "p-4 flex flex-col gap-2.5",
  cardHeader: "flex justify-between items-start mb-4",
  cardTitle: "text-base font-bold text-white tracking-wide break-words",
  cardCategory: "text-xs font-medium text-purple-400 uppercase tracking-wider",
  cardIcons: "flex items-center gap-3 pt-1",
  cardIconAction: "w-4 h-4 text-gray-400 hover:text-white transition-colors cursor-pointer",
  pinIconActive: "w-4 h-4 text-[#EF4444] cursor-pointer drop-shadow-[0_0_8px_rgba(239,68,68,0.5)]",
  pinIconInactive: "w-4 h-4 text-gray-400 hover:text-white cursor-pointer transition-colors",
  
  cardDesc: "text-sm text-gray-400 font-medium leading-relaxed mb-6 flex-1",
  
  cardFooter: "flex flex-row justify-between pt-3 border-t border-white/5 mt-auto",
  cardFooterRow: "flex items-center gap-1.5 text-[11px] font-semibold text-[#8FA0C4]",
  
  fab: "fixed bottom-10 right-10 w-[56px] h-[56px] rounded-full border-[1.5px] border-white/20 bg-transparent flex items-center justify-center text-white hover:border-white/50 hover:bg-white/5 transition-all cursor-pointer z-50 shadow-[0_0_20px_rgba(0,0,0,0.5)] hover:shadow-[0_0_25px_rgba(255,255,255,0.1)]",
  
  modalOverlay: "fixed inset-0 bg-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4",
  modalDialog: "w-full max-w-md bg-[#0B1333] border border-white/10 rounded-[24px] shadow-[0_20px_60px_rgba(0,0,0,0.8)] overflow-hidden flex flex-col relative",
  modalHeader: "flex items-center justify-between p-6 pb-4 border-b border-white/5",
  modalTitleWrap: "flex flex-col",
  modalTitle: "text-xl font-bold text-white tracking-tight",
  modalSubtitle: "text-sm text-gray-400 font-medium",
  modalCloseBtn: "text-gray-400 hover:text-white transition-colors cursor-pointer w-8 h-8 flex items-center justify-center rounded-full hover:bg-white/5",
  modalBody: "p-6 flex flex-col gap-5",
  inputGroup: "flex flex-col gap-2",
  inputLabel: "text-[13px] font-semibold text-gray-300 ml-1 uppercase tracking-wider",
  inputField: "w-full bg-[#131B3E] border border-white/10 focus:border-[#8B5CF6]/50 rounded-xl px-4 py-3.5 text-sm text-white placeholder-gray-500 focus:outline-none transition-all focus:shadow-[0_0_15px_rgba(139,92,246,0.15)]",
  textareaField: "w-full bg-[#131B3E] border border-white/10 focus:border-[#8B5CF6]/50 rounded-xl px-4 py-3.5 text-sm text-white placeholder-gray-500 focus:outline-none transition-all resize-none min-h-[100px] focus:shadow-[0_0_15px_rgba(139,92,246,0.15)]",
  modalFooter: "p-6 pt-4 flex justify-end gap-3 bg-[#080E29] border-t border-white/5",
  btnCancel: "px-5 py-2.5 rounded-xl text-sm font-semibold text-gray-300 hover:text-white hover:bg-white/5 transition-colors cursor-pointer",
  btnCreate: "px-6 py-2.5 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white rounded-xl text-sm font-semibold shadow-[0_0_15px_rgba(139,92,246,0.3)] transition-all cursor-pointer",
};
